export enum AllUseCases {
    CreateApartmentType = 1,
    RegisterUser = 2,
    GetAllUsers = 4,
    UpdateUserUseCases = 5,
    GetUser = 6,
    DeleteUser = 7,
    UpdateUser = 8,
    CreateApartment = 9,
    CreateCity = 10,
    CreateCountry = 11,
    CreateFeatures = 12,
    CreatePayment = 13,
    AddCityInCountry = 14,
    GetAllApartments = 15,
    GetApartmentInfo = 16,
    DeleteApartment = 17,
    UpdateApartment = 18,
    UpdateApartmentImages = 19,
    CreateBooking = 20,
    UpdateBooking = 21,
    CancelBooking = 22,
    GetMyBookings = 23,
    GetBookingInfo = 24,
    GetCities = 25,
    GetCountries = 26,
    GetApartmentTypes = 27, 
    GetApartmentFeatures = 28, 
    GetPayments = 29, 
    GetUseCaseLogs = 30,
    GetErrorLogs = 31,
    GetCitiesByCountry = 32,
    ChangeProfilePhoto = 33,
    SendMessageSignalR = 34,
    GetUserChatList = 35,
    GetUserChatMessages = 36,
    GetMyGyestBookings = 37,
    PrepareChat = 38,
    AddApartmentToFavorite = 39, 
    GetFavoriteApartments = 40,
    AddRating = 41,
    GetRatings = 42,
    ArchiveApartment = 43,
    GetArchivedApartments = 44,
    ActivateApartment = 45,
    ConfirmEmail = 46,
    ResendCode = 47, 
    ForgotPasswordSendEmail = 48, 
    ForgotPasswordCheckCode = 49,
    ChangePassword = 50,
    GoogleOAuth = 51,
    InitOpenAiMessage = 52,
    ContinueOpenAiConversation = 53, 
    GetAdminDashboard = 54, 
    GetAdminApartments = 55, 
    GetAdminApartmentFilters = 56, 
    GetAdminUsers = 57, 
    GetUserUseCases = 58, 
    GetBookingsAdmin = 59, 
    GetAdminCities = 60, 
    UpdatePaymentMethod = 61, 
    UpdateCity = 62, 
    UpdateApartmentType = 63,
    UpdateApartmentFeature = 64,
    GetHomeStats = 65,
    GetHomeTestimonials = 66,
}


export enum UserUseCases {
    DeleteUser = AllUseCases.DeleteUser,
    UpdateUser = AllUseCases.UpdateUser,
    CreateApartment = AllUseCases.CreateApartment,
    GetAllApartments = AllUseCases.GetAllApartments,
    GetApartmentInfo = AllUseCases.GetApartmentInfo,
    DeleteApartment = AllUseCases.DeleteApartment,
    UpdateApartment = AllUseCases.UpdateApartment,
    UpdateApartmentImages = AllUseCases.UpdateApartmentImages,
    CreateBooking = AllUseCases.CreateBooking,
    UpdateBooking = AllUseCases.UpdateBooking,
    CancelBooking = AllUseCases.CancelBooking,
    GetMyBookings = AllUseCases.GetMyBookings,
    GetBookingInfo = AllUseCases.GetBookingInfo,
    ChangeProfilePhoto = AllUseCases.ChangeProfilePhoto,
    SendMessageSignalR = AllUseCases.SendMessageSignalR,
    GetUserChatList = AllUseCases.GetUserChatList,
    GetUserChatMessages = AllUseCases.GetUserChatMessages,
    GetMyGyestBookings = AllUseCases.GetMyGyestBookings,
    PrepareChat = AllUseCases.PrepareChat,
    AddApartmentToFavorite = AllUseCases.AddApartmentToFavorite,
    GetFavoriteApartments = AllUseCases.GetFavoriteApartments,
    AddRating = AllUseCases.AddRating,
    ArchiveApartment = AllUseCases.ArchiveApartment,
    GetArchivedApartments = AllUseCases.GetArchivedApartments,
    ActivateApartment = AllUseCases.ActivateApartment,
}

export enum GloballyAllowedUseCases { 
  RegisterUser = AllUseCases.RegisterUser,
  GetUser = AllUseCases.GetUser,
  GetCities = AllUseCases.GetCities,
  GetCountries = AllUseCases.GetCountries,
  GetApartmentTypes = AllUseCases.GetApartmentTypes,
  GetApartmentFeatures = AllUseCases.GetApartmentFeatures,
  GetPayments = AllUseCases.GetPayments,
  GetCitiesByCountry = AllUseCases.GetCitiesByCountry,
  ConfirmEmail = AllUseCases.ConfirmEmail,
  ResendCode = AllUseCases.ResendCode,
  ForgotPasswordSendEmail = AllUseCases.ForgotPasswordSendEmail,
  ForgotPasswordCheckCode = AllUseCases.ForgotPasswordCheckCode,
  ChangePassword = AllUseCases.ChangePassword,
  GoogleOAuth = AllUseCases.GoogleOAuth,
  InitOpenAiMessage = AllUseCases.InitOpenAiMessage,
  ContinueOpenAiConversation = AllUseCases.ContinueOpenAiConversation,
  GetAdminCities = AllUseCases.GetAdminCities,
  GetHomeStats = AllUseCases.GetHomeStats,
  GetHomeTestimonials = AllUseCases.GetHomeTestimonials,
}

export enum AdminUseCases {
  //GetAllUsers = AllUseCases.GetAllUsers,
  //DeleteUser = AllUseCases.DeleteUser,
  UpdateUserUseCases = AllUseCases.UpdateUserUseCases,
  GetUseCaseLogs = AllUseCases.GetUseCaseLogs,
  GetErrorLogs = AllUseCases.GetErrorLogs,
  AdminDashboard = AllUseCases.GetAdminDashboard,
  GetAdminApartments = AllUseCases.GetAdminApartments,
  GetAdminFilters = AllUseCases.GetAdminApartmentFilters,
  GetAdminUsers = AllUseCases.GetAdminUsers,
  GetUserUseCases = AllUseCases.GetUserUseCases,
  GetBookingsAdmin = AllUseCases.GetBookingsAdmin,
  UpdatePaymentMethod = AllUseCases.UpdatePaymentMethod,
  AddPaymentMethod = AllUseCases.CreatePayment,
  AddCityInCountry = AllUseCases.AddCityInCountry,
  UpdateCity = AllUseCases.UpdateCity,
  AddApartmentType = AllUseCases.CreateApartmentType,
  UpdateApartmentType = AllUseCases.UpdateApartmentType,
  AddFeatures = AllUseCases.CreateFeatures,
  UpdateApartmentFeature = AllUseCases.UpdateApartmentFeature,
  AdminSettings = AllUseCases.RegisterUser, // fixed to enable settings page
}


//3 nema